"""agrega customer_email a Reservation

Revision ID: 3f4ce69ce17a
Revises: 4dcd36bd6847
Create Date: 2026-07-18 13:07:28.911820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4ce69ce17a'
down_revision: Union[str, None] = '4dcd36bd6847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservation', sa.Column('customer_email', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservation', 'customer_email')
    # ### end Alembic commands ###
