"""agrega is_active a Movie Room MovieFunction

Revision ID: 4dcd36bd6847
Revises: 8198c1721af9
Create Date: 2026-07-18 12:02:51.655886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dcd36bd6847'
down_revision: Union[str, None] = '8198c1721af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajustado a mano: autogenerate no agrega server_default, y agregar una
    # columna NOT NULL sin default falla contra una tabla con filas (Movie,
    # Room y MovieFunction ya tienen datos de seed/pruebas). Se agrega con
    # un server_default temporal para poblar las filas existentes y después
    # se lo quita: el modelo solo declara default=True del lado de Python
    # (sin server_default), dejarlo puesto desincronizaría el próximo
    # autogenerate contra el estado real de la tabla.
    op.add_column('Movie', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.alter_column('Movie', 'is_active', server_default=None)

    op.add_column('MovieFunction', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.alter_column('MovieFunction', 'is_active', server_default=None)

    op.add_column('Room', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.alter_column('Room', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Room', 'is_active')
    op.drop_column('MovieFunction', 'is_active')
    op.drop_column('Movie', 'is_active')
    # ### end Alembic commands ###
