"""esquema inicial

Revision ID: 8198c1721af9
Revises: 
Create Date: 2026-07-17 15:28:15.821323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8198c1721af9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('movie_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_min', sa.SmallInteger(), nullable=False),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('Room',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('admin','taquillero')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('MovieFunction',
    sa.Column('function_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movie.movie_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['Room.room_id'], ),
    sa.PrimaryKeyConstraint('function_id')
    )
    op.create_table('Seat',
    sa.Column('seat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(length=1), nullable=False),
    sa.Column('seat_number', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['Room.room_id'], ),
    sa.PrimaryKeyConstraint('seat_id'),
    sa.UniqueConstraint('room_id', 'row_label', 'seat_number', name='ux_seat_room_row_number')
    )
    op.create_table('Reservation',
    sa.Column('reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('Reservada','Confirmada','Utilizada','Cancelada','Expirada')", name='ck_reservation_status'),
    sa.ForeignKeyConstraint(['created_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['MovieFunction.function_id'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    op.create_index(op.f('ix_Reservation_created_by'), 'Reservation', ['created_by'], unique=False)
    op.create_index(op.f('ix_Reservation_function_id'), 'Reservation', ['function_id'], unique=False)
    op.create_index(op.f('ix_Reservation_status'), 'Reservation', ['status'], unique=False)
    op.create_table('ActiveSeatReservation',
    sa.Column('active_seat_reservation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['MovieFunction.function_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservation.reservation_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['Seat.seat_id'], ),
    sa.PrimaryKeyConstraint('active_seat_reservation_id'),
    sa.UniqueConstraint('function_id', 'seat_id', name='ux_active_seat_reservation')
    )
    op.create_table('ReservationSeat',
    sa.Column('reservation_seat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['MovieFunction.function_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservation.reservation_id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['Seat.seat_id'], ),
    sa.PrimaryKeyConstraint('reservation_seat_id'),
    sa.UniqueConstraint('reservation_id', 'seat_id', name='ux_reservation_seat')
    )
    op.create_table('ReservationStatusHistory',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('Reservada','Confirmada','Utilizada','Cancelada','Expirada')", name='ck_history_from_status'),
    sa.CheckConstraint("to_status IN ('Reservada','Confirmada','Utilizada','Cancelada','Expirada')", name='ck_history_to_status'),
    sa.ForeignKeyConstraint(['changed_by'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservation.reservation_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('Ticket',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reservation_seat_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=20), nullable=False),
    sa.Column('ticket_code', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_seat_id'], ['ReservationSeat.reservation_seat_id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('reservation_seat_id'),
    sa.UniqueConstraint('ticket_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ticket')
    op.drop_table('ReservationStatusHistory')
    op.drop_table('ReservationSeat')
    op.drop_table('ActiveSeatReservation')
    op.drop_index(op.f('ix_Reservation_status'), table_name='Reservation')
    op.drop_index(op.f('ix_Reservation_function_id'), table_name='Reservation')
    op.drop_index(op.f('ix_Reservation_created_by'), table_name='Reservation')
    op.drop_table('Reservation')
    op.drop_table('Seat')
    op.drop_table('MovieFunction')
    op.drop_table('User')
    op.drop_table('Room')
    op.drop_table('Movie')
    # ### end Alembic commands ###
